language: python
dist: xenial
cache: pip
install: travis_retry pip install -U tox
script: tox
jobs:
  fast_finish: true
  include:
  - { python: '3.8', env: TOXENV=lint }
  - { python: '2.7', env: TOXENV=py27 }
  - { python: '3.5', env: TOXENV=py35 }
  - { python: '3.6', env: TOXENV=py36 }
  - { python: '3.7', env: TOXENV=py37 }
  - { python: '3.8', env: TOXENV=py38 }
  - { python: '3.9-dev', env: TOXENV=py39 }

  - stage: PyPI Release
    if: tag IS present
    python: "3.8"
    env: []
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: sloria
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: oYZ97xz/ZhylohjrvClpFOURvlXCxFig4KMfAg0cuuL1TLNXalAnYnWebZN9srVmBDZ324aAHt9VZnCtZCXORhkMTDsBTnOrWkb0jsnxFN2PFP9KARLltiVknvTZb6Uy70XsMlKW920CWUKI+voAI9agbUETaxtc212jo3yHkxYQGtfTfURfQCZhYYoLK45v04Rm/HSQHGgUlg8xOJm/uJTC2xpPOWJv3XkoXfS18p0g0IsrVbtNdAvJ+IOJbRig2Qoq0vMXiNMArJPDTP1scjME5qKexN+5UpVzsUfm6254PK0d/Ap2DMOcZVPlxXIIMHoN5gpwOSN3SAtfbb5NvJbtNRjB12erzw+0DtB8ibJ3DxrOMJAihXkd8REIcqOU3Hsmh+1PKUkYfHjbk0SUb0AupllxgiP1Bp5fQBwPEp+he9atJAkAY9hr7EK0JqQ12DrtUgQ9kqDbz26Ad0II4R9M7xfJdPRljS9QY9RjTemnlcM+4rya7PzmblYqAYjedfb5zSAdyTEY9Px/e8pscKdpisLPGHpnwFCoAlaGtq5NzmzcqaoRImkl6B3YloapuCTs8RVwP0Me42qXSuGr+ocZTumxvt9a8bwoMOxyZX6Il65JmwaiR2BLY8cRjl9AQKhWcAyjNXYCdn454xO3QMtFhqm3+1zmEdHcltbdCVY=
